spring:
  application:
    name: gateway
services:
  core:
    url: http://chokak-server:8084
  storage:
    url: http://chokak-cloud-storage:8088
server:
  port: 8000

firebase:
  credentials:
    path: classpath:firebase-service-account.json