name: CI Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create secret JSON file
        run: |
          cat <<EOF > src/resources/firebase-service-account.json
          ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          EOF

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn -B test --file pom.xml

      - name: Cleanup secret file
        if: always()
        run: rm -f src/resources/firebase-service-account.json
